// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxkxqtsgeneaiocxdboh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4a3hxdHNnZW5lYWlvY3hkYm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MzczNjYsImV4cCI6MjA5MzQxMzM2Nn0.5RjeFZ4l4tkas0muQ2f_0yWCDbVbIjTul_JoRj_SPfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});